# Generated by Django 4.2 on 2024-06-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leftkomendacje", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="is_duplicate",
            field=models.BooleanField(default=False),
        ),
    ]
