# Generated by Django 4.2 on 2024-06-16 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leftkomendacje", "0003_alter_comment_parent_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="is_reply",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="parent_comment",
        ),
        migrations.AddField(
            model_name="comment",
            name="replies",
            field=models.ManyToManyField(blank=True, to="leftkomendacje.comment"),
        ),
    ]
