# Generated by Django 4.2 on 2024-06-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leftkomendacje", "0004_remove_comment_is_reply_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="replies",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leftkomendacje.comment",
            ),
        ),
    ]
